# Generated by Django 5.0.7 on 2024-08-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('JČ', 'Jihočeský'), ('JM', 'Jihomoravský'), ('KH', 'Královéhradecký'), ('LB', 'Liberecký'), ('MK', 'Moravskoslezský'), ('OL', 'Olomoucký'), ('PA', 'Pardubický'), ('PJ', 'Plzeňský'), ('PR', 'Praha'), ('ST', 'Středočeský'), ('UT', 'Ústecký'), ('EV', 'Evropa')], default='JČ', max_length=2)),
                ('web', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('JČ', 'Jihočeský'), ('JM', 'Jihomoravský'), ('KH', 'Královéhradecký'), ('LB', 'Liberecký'), ('MK', 'Moravskoslezský'), ('OL', 'Olomoucký'), ('PA', 'Pardubický'), ('PJ', 'Plzeňský'), ('PR', 'Praha'), ('ST', 'Středočeský'), ('UT', 'Ústecký'), ('EV', 'Evropa')], default='JČ', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('EA', 'Snadná'), ('MD', 'Středně náročná'), ('HD', 'Náročná')], default='EA', max_length=2)),
            ],
        ),
    ]
